# -*- coding: utf-8 -*-
"""Kafka_Consumer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e694JN9KTeFWOU4yNQKm56g4g4haO-Ty
"""

!pip install kafka-python
!pip install s3fs
from kafka import KafkaConsumer
from time import sleep
from json import dumps,loads
import json
from s3fs import S3FileSystem

consumer = KafkaConsumer(
    'demo_test',
     bootstrap_servers=['add your public ip address here'],
    value_deserializer=lambda x: loads(x.decode('utf-8')))

#for c in consumer:
  #print(c.value)

s3 = S3FileSystem()

#import s3fs

# Initialize S3 file system with credentials
s3 = S3FileSystem(key='YOUR_ACCESS_KEY', secret='YOUR_SECRET_KEY')

for count, i in enumerate(consumer):
    with s3.open(f"s3://kafka-stco-market-aayush/stock_market_{count}.json", 'w') as file:
        json.dump(i.value, file)
